.include <bsd.own.mk>

PROG= colour_sensor_hds
BINDIR= /etc/eniac/colour_sensor/colour_sensor_hds
SRCS= colour_sensor_hds.c
MAN=	

.include <bsd.prog.mk>

beforeinstall: 
	${INSTALL} -d $(DESTDIR)$(BINDIR)
